# Generated by Django 3.2 on 2023-01-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoss',
            name='image',
            field=models.ImageField(upload_to='static/uploads'),
        ),
    ]
